from eefr.knowledge_viewer.pages.implementations.CalculateRankSamplingPage import CalculateRankSamplingPage
from eefr.knowledge_viewer.pages.implementations.CalculateWeightsSamplingPage import CalculateWeightsSamplingPage
from eefr.knowledge_viewer.pages.implementations.ConstructorPage import ConstructorPage
from eefr.knowledge_viewer.pages.implementations.DiscretizerPage import DiscretizerPage
from eefr.knowledge_viewer.pages.implementations.EnsembleFeatureRankingPage import EnsembleFeatureRankingPage
from eefr.knowledge_viewer.pages.implementations.GetNRandomRowsSubsetsPage import GetNRandomRowsSubsetsPage
from eefr.knowledge_viewer.pages.implementations.MainPage import MainPage
from eefr.knowledge_viewer.pages.implementations.MetricPage import MetricPage
