from xefr4py.knowledge_viewer.pages.BasePage import BasePage
from xefr4py.knowledge_viewer.pages.BasePageWithBlockDiagram import BasePageWithBlockDiagram
from xefr4py.knowledge_viewer.pages.ChildPage import ChildPage
from xefr4py.knowledge_viewer.pages.ChildPageWithBlockDiagram import ChildPageWithBlockDiagram
