from xefr4py.knowledge_viewer.pages.implementations.CalculateRankSamplingPage import CalculateRankSamplingPage
from xefr4py.knowledge_viewer.pages.implementations.CalculateWeightsSamplingPage import CalculateWeightsSamplingPage
from xefr4py.knowledge_viewer.pages.implementations.ConstructorPage import ConstructorPage
from xefr4py.knowledge_viewer.pages.implementations.DiscretizerPage import DiscretizerPage
from xefr4py.knowledge_viewer.pages.implementations.EnsembleFeatureRankingPage import EnsembleFeatureRankingPage
from xefr4py.knowledge_viewer.pages.implementations.GetNRandomRowsSubsetsPage import GetNRandomRowsSubsetsPage
from xefr4py.knowledge_viewer.pages.implementations.MainPage import MainPage
from xefr4py.knowledge_viewer.pages.implementations.MetricPage import MetricPage
