from eefr.knowledge_viewer.Page.implementations.CalculateRankSamplingPage import CalculateRankSamplingPage
from eefr.knowledge_viewer.Page.implementations.CalculateWeightsSamplingPage import CalculateWeightsSamplingPage
from eefr.knowledge_viewer.Page.implementations.ConstructorPage import ConstructorPage
from eefr.knowledge_viewer.Page.implementations.DiscretizerPage import DiscretizerPage
from eefr.knowledge_viewer.Page.implementations.EnsembleFeatureRankingPage import EnsembleFeatureRankingPage
from eefr.knowledge_viewer.Page.implementations.GetNRandomRowsSubsetsPage import GetNRandomRowsSubsetsPage
from eefr.knowledge_viewer.Page.implementations.MainPage import MainPage
from eefr.knowledge_viewer.Page.implementations.MetricPage import MetricPage
